database:
  url: "mongodb+srv://dbUser:NotAPassword123@flightbookercluster.zia92pq.mongodb.net/?retryWrites=true&w=majority&appName=FlightBookerCluster"
  dbname: "FlightBooker"

server:
  port: "8080"

app:
  name: "appdoc-api"
  timeout: 3000